# Generated by Django 5.2.15 on 2026-06-26 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_alter_evaluation_judge_alter_evaluation_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.judge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.team')),
            ],
            options={
                'unique_together': {('judge', 'team')},
            },
        ),
    ]
